---

- name: apply common configuration to all nodes
  hosts: auth
  remote_user: ubuntu
  vars_files:
    - vars/secret.yml

  roles:
    - ansiblebit.launchpad-ppa-webupd8
    - ansiblebit.oracle-java
    - role: Datadog.datadog
      become: true
      become_method: sudo

- name: apply configuration for media servers
  hosts: media
  roles:
    - media
    - franklinkim.environment
  vars_files:
    - vars/secret.yml

- name: apply configuration for signaling servers
  hosts: signaling
  roles:
    - signaling
    - franklinkim.environment
    - geerlingguy.nodejs
  vars_files:
    - vars/secret.yml

- name: apply configuration for auth servers
  hosts: auth
  roles:
    - auth
    - franklinkim.environment
  vars_files:
    - vars/secret.yml

- name: apply configuration for recording servers
  hosts: recording
  roles:
    - recording
    - franklinkim.environment
  vars_files:
    - vars/secret.yml

- name: apply configuration for demo servers
  hosts: demo
  roles:
    - demo
    - franklinkim.environment
    - geerlingguy.apache
  vars_files:
    - vars/secret.yml
