#!/bin/sh
# /etc/init.d/teamcity -  startup script for teamcity
export TEAMCITY_DATA_PATH="/srv/.BuildServer"
export PATH="$PATH:/sbin"

case $1 in
  start)
    if [ -f  /home/teamcity/.first-run ]
    then
        echo "Starting TeamCity"
        start-stop-daemon --start -c teamcity --exec /srv/TeamCity/bin/teamcity-server.sh start
    fi
    ;;

  stop)
    echo "Stopping TeamCity"
    start-stop-daemon --start -c teamcity --exec  /srv/TeamCity/bin/teamcity-server.sh stop
    ;;

  restart)
    echo "Restarting TeamCity"
    start-stop-daemon --start -c teamcity --exec /srv/TeamCity/bin/teamcity-server.sh stop
    start-stop-daemon --start -c teamcity --exec /srv/TeamCity/bin/teamcity-server.sh start
    ;;
  *)
    echo "Usage: /etc/init.d/teamcity {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
